image: "ruby:2.6"

variables:
  RAILS_ENV: "test"
  POSTGRES_DB: registry_test
  POSTGRES_USER: registry
  POSTGRES_PASSWORD: Password!1

stages:
  - build
  - test
  - deploy

build:
  services:
    - postgres:latest
  stage: build
  script:
  - ruby -v
  - which ruby
  - gem install bundler 
  - bundle install --jobs 20 --retry 5
  - RAILS_ENV=test bundle exec rake db:create_db_with_public_data db:migrate
  - RAILS_ENV=test bundle exec rails assets:precompile

integration_test:
  stage: test
  services:
    - postgres:latest
  script:
    - gem install bundler  --no-ri --no-rdoc
    - bundle install  --jobs $(nproc) "${FLAGS[@]}" 
    - RAILS_ENV=test bundle exec rake db:create_db_with_public_data db:migrate
    - RAILS_ENV=test bundle exec rails assets:precompile
    - bundle exec rake test
