FROM certbot/certbot as certbot-prod

# install nginx
RUN apt-get update -y
RUN apt-get install -y software-properties-common

# install certbot
RUN add-apt-repository ppa:certbot/certbot
RUN apt-get update -y
RUN apt-get install -y certbot python-certbot-nginx

# expose ports
EXPOSE 80 443
