version: '3.7'
services:
 nginx:
  build:
    context: .
    dockerfile: Dockerfile-nginx
    target: nginx-prod
  restart: unless-stopped
  volumes:
   - ./prod/ssl/data/nginx/nginx.conf:/etc/nginx/nginx.conf
   - ./prod/ssl/data/nginx/dev:/etc/nginx/conf.d
   - ./prod/ssl/data/certbot/conf:/etc/letsencrypt
   - ./prod/ssl/data/certbot/www:/var/www/certbot
   - ./public:/var/www/registry
  ports:
   - 80:80
   - 443:443
  entrypoint: /t4d/docker-entrypoint-nginx.sh 
