version: "3.7"

# External services required to run the Catalog: PostgreSQL and Redis.
# Requires an .env file in the CWD with the variables used in this file.

services:
  redis:
    image: redis
    command: "--requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}"
    environment:
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - catalog-data-dev:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
  remark42:
    image: umputun/remark42:latest
    container_name: "remark42"
    ports:
        - 8081:8080
    environment:
        - AUTH_EMAIL_ENABLE=true
        - AUTH_ANON=true
        - REMARK_URL=http://localhost
        - SITE=solutions
        - SECRET=abcd
        - ADMIN_PASSWD=1234
    volumes:
        - ./comments:/srv/var

volumes:
  catalog-data-dev:
