version: '3.7'
services:
 nginx:
  image: nginx:1.19
  restart: unless-stopped
  volumes:
   - ./prod/ssl/data/nginx/nginx.conf:/etc/nginx/nginx.conf
   - ./prod/ssl/data/nginx/dev:/etc/nginx/conf.d
   - ./prod/ssl/data/certbot/conf:/etc/letsencrypt
   - ./prod/ssl/data/certbot/www:/var/www/certbot
   - ./public:/var/www/registry
  ports:
   - 80:80
   - 443:443
  command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
 certbot:
  build:
    context: .
    dockerfile: Dockerfile-certbot
    target: certbot-prod
  restart: unless-stopped
  volumes:
   - ./prod/ssl/data/certbot/conf:/etc/letsencrypt
   - ./prod/ssl/data/certbot/www:/var/www/certbot
  entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
 
