version: "3.7"
services:
  exchange-backend:
    # image: localhost:5000/t4d-product-backlog:${T4D_VERSION}
    build:
      context: .
      target: build-web
      additional_contexts:
        gdpir: ../www.dpi.global
    environment:
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_ENV=production
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - CHATBOT_BASE_URL='http://exchange-chatbot:8000'
    entrypoint: /t4d/docker-entrypoint.sh
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    restart: always
    volumes:
      - .:/t4d
      - ./prod/logrotate.d/registry:/etc/logrotate.d/registry
    ports:
      - 80:3000
  exchange-frontend:
    build:
      context: ../exchange-frontend/
      target: prod
    working_dir: /app
    user: nextjs
    stdin_open: true
    restart: always
    ports:
      - 3002:3002
    command: yarn start
    depends_on:
      - exchange-backend
  exchange-chatbot:
    build:
      context: ../exchange-chatbot/
    ports:
      - 8000:8000
  playbooks:
    build: '../playbooks'
    entrypoint: '/playbooks/docker-entrypoint.sh'
    tty: true
    stdin_open: true # without this node doesn't start
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - exchange-backend
      - exchange-frontend
