version: "3.7"

# External services required to run the Catalog: PostgreSQL and Redis.
# Requires an .env file in the CWD with the variables used in this file.

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - catalog-data-dev:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

volumes:
  catalog-data-dev:
