version: "3.7"
services:
  exchange-backend:
    # image: localhost:5000/t4d-product-backlog:${T4D_VERSION}
    build:
      context: .
      target: build-web2
    environment:
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_ENV=production
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    entrypoint: /t4d/docker-entrypoint2.sh
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    restart: always
    volumes:
      - .:/t4d
      - ./prod/logrotate.d/registry:/etc/logrotate.d/registry
      - type: volume
        source: assets
        target: /t4d/public
        volume:
          nocopy: true
    ports:
      - 80:3000
  exchange-frontend:
    build:
      context: ../exchange-frontend/
      target: prod
    working_dir: /app
    user: nextjs
    stdin_open: true
    ports:
      - 3002:3002
    command: yarn start
  playbooks:
    build: '../playbooks'
    entrypoint: '/playbooks/docker-entrypoint.sh'
    tty: true
    stdin_open: true # without this node doesn't start
    restart: always
    ports:
      - 3001:3001
volumes:
  assets:
    driver_opts:
      type: "nfs"
      o: "addr=exchangeapp01.dial.global,nolock,soft,rw"
      device: ":/root/product-registry/public"

