---
swagger: '2.0'
info:
  title: API v1
  version: v1
paths:
  "/api/v1/building_blocks/{slug}":
    get:
      summary: Retrieves a building block.
      tags:
      - Building Blocks
      produces:
      - application/json
      parameters:
      - name: slug
        in: path
        type: string
        required: true
      responses:
        '200':
          description:
            description: Success.
        '404':
          description:
            description: 'Error: Not Found.'
  "/api/v1/building_blocks":
    get:
      summary: Search for building blocks.
      tags:
      - Building Blocks
      produces:
      - application/json
      parameters:
      - name: search
        in: query
        schema:
          type: string
        description: Search term to narrow results.
      - name: page
        in: query
        schema:
          type: integer
        description: Page to narrow results.
      responses:
        '200':
          description:
            description: Success.
    post:
      summary: Search for building blocks.
      tags:
      - Building Blocks
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: search
        in: query
        schema:
          type: string
        description: Search term to narrow results.
      - name: page
        in: query
        schema:
          type: integer
        description: Page to narrow results.
      - name: request_body
        in: body
        schema:
          type: object
          properties:
            sdgs:
              type: array
              description: SDG
              items:
                type: string
            use_cases:
              type: array
              items:
                type: string
            workflows:
              type: array
              items:
                type: string
            building_blocks:
              type: array
              items:
                type: string
            products:
              type: array
              items:
                type: string
        description: JSON to narrow results.
      responses:
        '200':
          description:
            description: Success.
  "/api/v1/cities/{slug}":
    get:
      summary: Retrieves a city.
      tags:
      - Cities
      produces:
      - application/json
      parameters:
      - name: slug
        in: path
        type: string
        required: true
      responses:
        '200':
          description:
            description: Success.
        '404':
          description:
            description: 'Error: Not Found.'
  "/api/v1/cities":
    get:
      summary: Search for cities.
      tags:
      - Cities
      produces:
      - application/json
      parameters:
      - name: search
        in: query
        schema:
          type: string
        description: Search term to narrow results.
      - name: page
        in: query
        schema:
          type: integer
        description: Page to narrow results.
      responses:
        '200':
          description:
            description: Success.
  "/api/v1/countries/{slug}":
    get:
      summary: Retrieves a country.
      tags:
      - Countries
      produces:
      - application/json
      parameters:
      - name: slug
        in: path
        type: string
        required: true
      responses:
        '200':
          description:
            description: Success.
        '404':
          description:
            description: 'Error: Not Found.'
  "/api/v1/countries":
    get:
      summary: Search for countries.
      tags:
      - Countries
      produces:
      - application/json
      parameters:
      - name: search
        in: query
        schema:
          type: string
        description: Search term to narrow results.
      - name: page
        in: query
        schema:
          type: integer
        description: Page to narrow results.
      responses:
        '200':
          description:
            description: Success.
  "/api/v1/organizations/{slug}":
    get:
      summary: Retrieves an organization.
      tags:
      - Organizations
      produces:
      - application/json
      parameters:
      - name: slug
        in: path
        type: string
        required: true
      responses:
        '200':
          description:
            description: Success.
        '404':
          description:
            description: 'Error: Not Found.'
  "/api/v1/organizations":
    get:
      summary: Search for organizations.
      tags:
      - Organizations
      produces:
      - application/json
      parameters:
      - name: search
        in: query
        schema:
          type: string
        description: Search term to narrow results.
      - name: page
        in: query
        schema:
          type: integer
        description: Page to narrow results.
      responses:
        '200':
          description:
            description: Success.
    post:
      summary: Search for organizations.
      tags:
      - Organizations
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: search
        in: query
        schema:
          type: string
        description: Search term to narrow results.
      - name: page
        in: query
        schema:
          type: integer
        description: Page to narrow results.
      - name: request_body
        in: body
        schema:
          type: object
          properties:
            countries:
              type: array
              items:
                type: string
            sectors:
              type: array
              items:
                type: string
            endorsing_years:
              type: array
              items:
                type: string
        description: JSON to narrow results.
      responses:
        '200':
          description:
            description: Success.
  "/api/v1/products/{slug}":
    get:
      summary: Retrieves a product.
      tags:
      - Products
      produces:
      - application/json
      parameters:
      - name: slug
        in: path
        type: string
        required: true
      responses:
        '200':
          description:
            description: Success.
        '404':
          description:
            description: 'Error: Not Found.'
  "/api/v1/products":
    get:
      summary: Search for products.
      tags:
      - Products
      produces:
      - application/json
      parameters:
      - name: search
        in: query
        schema:
          type: string
        description: Search term to narrow results.
      - name: page
        in: query
        schema:
          type: integer
        description: Page to narrow results.
      responses:
        '200':
          description:
            description: Success.
    post:
      summary: Search for products.
      tags:
      - Products
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: search
        in: query
        schema:
          type: string
        description: Search term to narrow results.
      - name: page
        in: query
        schema:
          type: integer
        description: Page to narrow results.
      - name: request_body
        in: body
        schema:
          type: object
          properties:
            sdgs:
              type: array
              description: SDG
              items:
                type: string
            use_cases:
              type: array
              items:
                type: string
            workflows:
              type: array
              items:
                type: string
            building_blocks:
              type: array
              items:
                type: string
            products:
              type: array
              items:
                type: string
        description: JSON to narrow results.
      responses:
        '200':
          description:
            description: Success.
  "/api/v1/projects/{slug}":
    get:
      summary: Retrieves a project.
      tags:
      - Projects
      produces:
      - application/json
      parameters:
      - name: slug
        in: path
        type: string
        required: true
      responses:
        '200':
          description:
            description: Success.
        '404':
          description:
            description: 'Error: Not Found.'
  "/api/v1/projects":
    get:
      summary: Search for projects.
      tags:
      - Projects
      produces:
      - application/json
      parameters:
      - name: search
        in: query
        schema:
          type: string
        description: Search term to narrow results.
      - name: page
        in: query
        schema:
          type: integer
        description: Page to narrow results.
      responses:
        '200':
          description:
            description: Success.
  "/api/v1/sectors/{slug}":
    get:
      summary: Retrieves a sector.
      tags:
      - Sectors
      produces:
      - application/json
      parameters:
      - name: slug
        in: path
        type: string
        required: true
      responses:
        '200':
          description:
            description: Success.
        '404':
          description:
            description: 'Error: Not Found.'
  "/api/v1/sectors":
    get:
      summary: Search for sectors.
      tags:
      - Sectors
      produces:
      - application/json
      parameters:
      - name: search
        in: query
        schema:
          type: string
        description: Search term to narrow results.
      - name: page
        in: query
        schema:
          type: integer
        description: Page to narrow results.
      responses:
        '200':
          description:
            description: Success.
  "/api/v1/sdgs/{slug}":
    get:
      summary: Retrieves an sustainable development goals.
      tags:
      - Sustainable Development Goals
      produces:
      - application/json
      parameters:
      - name: slug
        in: path
        type: string
        required: true
      responses:
        '200':
          description:
            description: Success.
        '404':
          description:
            description: 'Error: Not Found.'
  "/api/v1/sdgs":
    get:
      summary: Search for sustainable development goals.
      tags:
      - Sustainable Development Goals
      produces:
      - application/json
      parameters:
      - name: search
        in: query
        schema:
          type: string
        description: Search term to narrow results.
      - name: page
        in: query
        schema:
          type: integer
        description: Page to narrow results.
      responses:
        '200':
          description:
            description: Success.
  "/api/v1/tags/{slug}":
    get:
      summary: Retrieves a tag.
      tags:
      - Tags
      produces:
      - application/json
      parameters:
      - name: slug
        in: path
        type: string
        required: true
      responses:
        '200':
          description:
            description: Success.
        '404':
          description:
            description: 'Error: Not Found.'
  "/api/v1/tags":
    get:
      summary: Search for tags.
      tags:
      - Tags
      produces:
      - application/json
      parameters:
      - name: search
        in: query
        schema:
          type: string
        description: Search term to narrow results.
      - name: page
        in: query
        schema:
          type: integer
        description: Page to narrow results.
      responses:
        '200':
          description:
            description: Success.
  "/api/v1/use_cases/{slug}":
    get:
      summary: Retrieves a use case.
      tags:
      - Use Cases
      produces:
      - application/json
      parameters:
      - name: slug
        in: path
        type: string
        required: true
      responses:
        '200':
          description:
            description: Success.
        '404':
          description:
            description: 'Error: Not Found.'
  "/api/v1/use_cases":
    get:
      summary: Search for use cases.
      tags:
      - Use Cases
      produces:
      - application/json
      parameters:
      - name: search
        in: query
        schema:
          type: string
        description: Search term to narrow results.
      - name: page
        in: query
        schema:
          type: integer
        description: Page to narrow results.
      responses:
        '200':
          description:
            description: Success.
    post:
      summary: Search for use cases.
      tags:
      - Use Cases
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: search
        in: query
        schema:
          type: string
        description: Search term to narrow results.
      - name: page
        in: query
        schema:
          type: integer
        description: Page to narrow results.
      - name: request_body
        in: body
        schema:
          type: object
          properties:
            sdgs:
              type: array
              description: SDG
              items:
                type: string
            use_cases:
              type: array
              items:
                type: string
            workflows:
              type: array
              items:
                type: string
            building_blocks:
              type: array
              items:
                type: string
            products:
              type: array
              items:
                type: string
        description: JSON to narrow results.
      responses:
        '200':
          description:
            description: Success.
  "/api/v1/workflows/{slug}":
    get:
      summary: Retrieves a workflow.
      tags:
      - Workflows
      produces:
      - application/json
      parameters:
      - name: slug
        in: path
        type: string
        required: true
      responses:
        '200':
          description:
            description: Success.
        '404':
          description:
            description: 'Error: Not Found.'
  "/api/v1/workflows":
    get:
      summary: Search for workflows.
      tags:
      - Workflows
      produces:
      - application/json
      parameters:
      - name: search
        in: query
        schema:
          type: string
        description: Search term to narrow results.
      - name: page
        in: query
        schema:
          type: integer
        description: Page to narrow results.
      responses:
        '200':
          description:
            description: Success.
    post:
      summary: Search for workflows.
      tags:
      - Workflows
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: search
        in: query
        schema:
          type: string
        description: Search term to narrow results.
      - name: page
        in: query
        schema:
          type: integer
        description: Page to narrow results.
      - name: request_body
        in: body
        schema:
          type: object
          properties:
            sdgs:
              type: array
              items:
                type: string
            use_cases:
              type: array
              items:
                type: string
            workflows:
              type: array
              items:
                type: string
            building_blocks:
              type: array
              items:
                type: string
            products:
              type: array
              items:
                type: string
        description: JSON to narrow results.
      responses:
        '200':
          description:
            description: Success.
