services:
  exchange-backend:
    # image: localhost:5000/t4d-product-backlog:${T4D_VERSION}
    build:
      context: ..
      target: build-web2
    environment:
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_ENV=production
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - CHATBOT_BASE_URL=http://exchange-chatbot:8080
    entrypoint: /t4d/docker-entrypoint2.sh
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    restart: always
    volumes:
      - .:/t4d
      - ./prod/logrotate.d/registry:/etc/logrotate.d/registry
      - type: volume
        source: assets
        target: /t4d/public
        volume:
          nocopy: true
    ports:
      - 80:3000
  exchange-frontend:
    build:
      context: ../../exchange-frontend/
      target: prod
    working_dir: /app
    user: nextjs
    stdin_open: true
    restart: always
    ports:
      - 3002:3002
    command: yarn start
    depends_on:
      - exchange-backend
  exchange-chatbot:
    build:
      context: ../../exchange-chatbot/
    ports:
      - 8080:8080
    volumes:
      - ./prod/chatbot/faiss-index:/faiss-index
      - ./prod/chatbot/record-manager:/record-manager
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FAISS_INDEX_PATH=/faiss-index
      - RECORD_MANAGER_PATH=/record-manager
      - EXCHANGE_API_BASE=http://exchange-backend:3000/api/v1
    depends_on:
      - exchange-backend
      - exchange-frontend
    restart: unless-stopped
  restarter:
    image: docker:cli
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep 86400; docker restart exchange-backend-exchange-chatbot-1; done"]
    restart: unless-stopped
  playbooks:
    build: '../../playbooks'
    entrypoint: '/playbooks/docker-entrypoint.sh'
    tty: true
    stdin_open: true # without this node doesn't start
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - exchange-backend
      - exchange-frontend
volumes:
  assets:
    driver_opts:
      type: "nfs"
      o: "addr=exchangeapp01.dial.global,nolock,soft,rw"
      device: ":/root/exchange-backend/public"

