version: '3.7'
services:
 nginx:
  build:
    context: .
    dockerfile: Dockerfile-nginx
    target: nginx-prod
  restart: unless-stopped
  volumes:
   - ../prod/ssl/data/nginx/nginx.conf:/etc/nginx/nginx.conf
   - ../prod/ssl/data/nginx/prod:/etc/nginx/conf.d
   - ../prod/ssl/data/certbot/conf:/etc/letsencrypt
   - ../prod/ssl/data/certbot/www:/var/www/certbot
   - ../public:/var/www/registry
   - ../cloudflare.ini:/t4d/cloudflare.ini
  ports:
   - 80:80
   - 443:443
  entrypoint: /t4d/deploy/docker-entrypoint-nginx.sh