FROM nginx:1.27 as nginx-prod

ARG PIP_BREAK_SYSTEM_PACKAGES=1

# install certbot
RUN apt update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    cargo \
    curl \
    libffi8 \
    libffi-dev \
    libssl-dev \
    openssl \
    pkg-config \
    procps \
    python3 \
    python3-dev \
    cron && \
    curl -L 'https://bootstrap.pypa.io/get-pip.py' | python3 && \
    pip3 install -U cffi certbot==2.11.0 certbot-nginx && \
    pip3 install -U cffi certbot==2.11.0 certbot-dns-cloudflare && \
    apt remove --purge -y build-essential cargo libffi-dev libssl-dev curl python3-dev && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# add entrypoint
RUN mkdir /t4d
WORKDIR /t4d
COPY cron-sync-nginx /etc/cron.d/cron-sync
RUN crontab /etc/cron.d/cron-sync
ADD docker-entrypoint-nginx.sh deploy/docker-entrypoint-nginx.sh
