# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  # <<: *default
  # database: db/development.sqlite3
  pool: 5
  timeout: 5000
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: registry_development
  username: registry
  password: "Password!1"
