development:
  esri:
    auth_uri: https://www.arcgis.com/sharing/rest/oauth2/token
    suggest_uri: https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/suggest
    geocode_uri: https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates
    client_id: <%= ENV["ESRI_CLIENT_ID"] %>
    client_secret: <%= ENV["ESRI_CLIENT_SECRET"] %>
    grant_type: client_credentials

test:
  esri:
    auth_uri: https://www.arcgis.com/sharing/rest/oauth2/token
    suggest_uri: https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/suggest
    geocode_uri: https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates
    client_id: <%= ENV["ESRI_CLIENT_ID"] %>
    client_secret: <%= ENV["ESRI_CLIENT_SECRET"] %>
    grant_type: client_credentials

production:
  esri:
    auth_uri: https://www.arcgis.com/sharing/rest/oauth2/token
    suggest_uri: https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/suggest
    geocode_uri: https://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/findAddressCandidates
    client_id: <%= ENV["ESRI_CLIENT_ID"] %>
    client_secret: <%= ENV["ESRI_CLIENT_SECRET"] %>
    grant_type: client_credentials