- category: Active Maintenance
  indicators:
    - name: Pull Requests
      low:
        - operator: greaterThan
          value: 10
      medium:
        - operator: greaterThan
          value: 2
        - operator: lessThan
          value: 9
      high:
        - operator: lessThan
          value: 1
    - name: Issues
      low:
        - operator: greaterThan
          value: 5
      medium:
        - operator: greaterThan
          value: 2
        - operator: lessThan
          value: 4
      high:
        - operator: lessThan
          value: 1
    - name: Last Repository Activity
      low:
        - operator: greaterThan
          value: 365
      medium:
        - operator: greaterThan
          value: 30
        - operator: lessThan
          value: 364
      high:
        - operator: lessThan
          value: 29
- category: Software Usage
  indicators:
    - name: Releases
      low:
        - operator: equalTo
          value: 0
      medium:
        - operator: greaterThan
          value: 1
        - operator: lessThan
          value: 9
      high:
        - operator: greaterThan
          value: 10
    - name: Downloads
      low:
        - operator: lessThan
          value: 9
      medium:
        - operator: greaterThan
          value: 10
        - operator: lessThan
          value: 99
      high:
        - operator: greaterThan
          value: 100
    - name: Stars
      low:
        - operator: lessThan
          value: 49
      medium:
        - operator: greaterThan
          value: 50
        - operator: lessThan
          value: 199
      high:
        - operator: greaterThan
          value: 200
    - name: Forks
      low:
        - operator: lessThan
          value: 9
      medium:
        - operator: greaterThan
          value: 10
        - operator: lessThan
          value: 49
      high:
        - operator: greaterThan
          value: 50
    - name: Watchers
      low:
        - operator: lessThan
          value: 9
      medium:
        - operator: greaterThan
          value: 10
        - operator: lessThan
          value: 99
      high:
        - operator: greaterThan
          value: 100
- category: Code Review
  indicators:
    - name: Language
      low:
        - operator: greaterThan
          value: 26
      medium:
        - operator: greaterThan
          value: 11
        - operator: lessThan
          value: 25
      high:
        - operator: lessThan
          value: 10

      