- category: Repository Info
  indicators:
    - name: Releases
      low:
        - operator: equalTo
          value: 0
      medium:
        - operator: greaterThan
          value: 1
        - operator: lessThan
          value: 9
      high:
        - operator: greaterThan
          value: 10
    - name: Commits
      low:
        - operator: lessThan
          value: 49
      medium:
        - operator: greaterThan
          value: 50
        - operator: lessThan
          value: 999
      high:
        - operator: greaterThan
          value: 1000
    - name: Downloads
      low:
        - operator: lessThan
          value: 9
      medium:
        - operator: greaterThan
          value: 10
        - operator: lessThan
          value: 99
      high:
        - operator: greaterThan
          value: 100
    - name: Stars
      low:
        - operator: lessThan
          value: 99
      medium:
        - operator: greaterThan
          value: 100
        - operator: lessThan
          value: 999
      high:
        - operator: greaterThan
          value: 1000
    - name: Forks
      low:
        - operator: lessThan
          value: 49
      medium:
        - operator: greaterThan
          value: 50
        - operator: lessThan
          value: 99
      high:
        - operator: greaterThan
          value: 100
    - name: Open Pull Requests
      low:
        - operator: lessThan
          value: 2
      medium:
        - operator: greaterThan
          value: 3
        - operator: lessThan
          value: 19
      high:
        - operator: greaterThan
          value: 20
    - name: Merged Pull Requests
      low:
        - operator: lessThan
          value: 49
      medium:
        - operator: greaterThan
          value: 50
        - operator: lessThan
          value: 499
      high:
        - operator: greaterThan
          value: 500
    - name: Open Issues
      low:
        - operator: lessThan
          value: 9
      medium:
        - operator: greaterThan
          value: 10
        - operator: lessThan
          value: 49
      high:
        - operator: greaterThan
          value: 50
    - name: Closed Issues
      low:
        - operator: lessThan
          value: 49
      medium:
        - operator: greaterThan
          value: 50
        - operator: lessThan
          value: 99
      high:
        - operator: greaterThan
          value: 100
    - name: Last Repository Activity
      low:
        - operator: greaterThan
          value: 365
      medium:
        - operator: greaterThan
          value: 30
        - operator: lessThan
          value: 364
      high:
        - operator: lessThan
          value: 29
    - name: Language
      low:
        - operator: greaterThan
          value: 26
      medium:
        - operator: greaterThan
          value: 11
        - operator: lessThan
          value: 25
      high:
        - operator: lessThan
          value: 10

      