  - item: mPowering Frontline Health Worker Initiative
  - item: Open Source LIS Community of Practice
  - item: Columbia International eHealth Lab's (CIEL) OpenMRS Concept Dictionary
  - item: Lorem Ipsum for Digital Health
  - item: Archive
  - item: CropPlanning
  - item: 5Calls Frontend
  - item: 5Calls iOS
  - item: Accessibility-cloud
  - item: Alex Atom Linter
  - item: Alex Sublime Linter
  - item: Android Guides
  - item: api.gouv.fr
  - item: Ask
  - item: Autofocus
  - item: Bias Correct
  - item: Blockly
  - item: Bob Emploi
  - item: Carbon Inferno
  - item: CGMBLEKit
  - item: Code For America Brigade Website
  - item: Community Health Toolkit
  - item: Croquemort
  - item: Deon
  - item: Dollar Street Pages
  - item: Energydata.info
  - item: Energy Web UI
  - item: Eviction Free NYC
  - item: Eviction Maps
  - item: Find Training
  - item: FoodCoops
  - item: Geolambda
  - item: Global Power Plant Data-Base
  - item: Heat Seek WebApp
  - item: HikmaHealth
  - item: Inclusion UKR
  - item: Infagram
  - item: Intake
  - item: JustFix NYC WebApp
  - item: Label Maker
  - item: Landsat Util
  - item: Leximpact
  - item: LittleSis Main
  - item: LittleSis Rails
  - item: LookingGlass
  - item: Madison
  - item: MathShare
  - item: Mes Aides - UI
  - item: Michigan Benefits
  - item: Mobile Kids Id App
  - item: Muckrock
  - item: MusicBlocks
  - item: Nosdeputes.fr
  - item: OADA Service Docker
  - item: OED
  - item: OneBusAway
  - item: OpenAI Spinning Up
  - item: Openbudgetoakland
  - item: Open Demographics
  - item: OpenFisca France
  - item: Open Government
  - item: Open Machine Learning
  - item: Open ML Python
  - item: Open MRS Concept Dictionary
  - item: Open Pantry
  - item: Operation Code Backend
  - item: Operation Code Front-End
  - item: Operation Code Pybot
  - item: Operation Code Pybot Backend
  - item: Operation Code Resources
  - item: Opt-Out
  - item: Otsimo AAC
  - item: Parliamentary Monitoring Group
  - item: Participatory Budgeting
  - item: Pathways Backend
  - item: PenText
  - item: Pixframe
  - item: PlayTime
  - item: Quill-NLP-Tools-and-Datasets
  - item: Rah-e-maa
  - item: Raster Vision
  - item: Refuge Restrooms
  - item: Refuge Restrooms iOS
  - item: RightOn Application
  - item: Ripple
  - item: Safe Water
  - item: SleepBus Website
  - item: Soulmedecine
  - item: Suzhou Crenator Labs
  - item: Tenants 2.0 - NYC
  - item: Unpaywall
  - item: Vessel Classification
  - item: VoiceApp311
  - item: WattTime Pysio
  - item: WattTime Python API
  - item: Wheel Map
  - item: Wheel Map Frontend
  - item: Who Owns What - NYC
  - item: World Cleanup Day
  - item: Zamba
  
