development: &development
  admin_email: 'admin@admin-user.org'
  installation_organization_key: 'default-organization'
  default_maturity_rubric_slug: 'default-maturity-rubric-slug'

test:
  <<: *development

production:
  <<: *development