tenants:
  - name: fao
    urls: 
      - url: fao.localhost
      - url: fao.dial.community
    allow_unsecure_read: false
    adminPassword: Admin123
  - name: health
    urls: 
      - url: health.localhost
      - url: health.dial.community
      - url: apps.africacdc.org
    allow_unsecure_read: true
    adminPassword: Admin123